name: Release General

on:
  push:
    tags:
      - '[0-9]*.*'

jobs:
  release:
    name: Build and upload release artifacts
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree ...
        uses: actions/checkout@v4
      - name: Setting release variables ...
        id: build
        run: |
          ver=${GITHUB_REF#refs/tags/}
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          if echo $ver | grep -qE '^[0-9]+\.[0-9]+(\.[0-9]+)?(-alpha|-beta|-rc)[0-9]*$'; then
            echo "pre=true"     >> $GITHUB_OUTPUT
            echo "latest=false" >> $GITHUB_OUTPUT
          elif echo $ver | grep -qE '^[0-9]+\.[0-9]+(\.[0-9]+)?$'; then
            echo "pre=false"    >> $GITHUB_OUTPUT
            echo "latest=true"  >> $GITHUB_OUTPUT
          else
            echo "pre=false"    >> $GITHUB_OUTPUT
            echo "latest=false" >> $GITHUB_OUTPUT
          fi
      - name: Check build ...
        run: make
      - name: Build release ...
        run: |
          make release
          mkdir -p artifacts/
          cp ../*.tar.* ../*.md5 ../*.sha* artifacts/
      - uses: ncipollo/release-action@v1
        with:
          name: Micro Tetris v${{ github.ref_name }}
          prerelease: ${{ steps.build.outputs.pre }}
          makeLatest: ${{ steps.build.outputs.latest }}
          artifacts: "artifacts/*"
